### ISSUE TITLE
Generate cut files

### ISSUE THREAD

**Issue by guanyilun** [bmalumphy/frb-analysis#13]
Running cut generation of Feynman takes 3 hours / 100 TOD. In each season there are 20000 TODs, so it will take about 25 days to generate all cuts. This can be done but on the other hand, according to Fernando, the original author of the cuts generate the cuts in the timescale of days. Therefore, it would be good to correspond with Fernando and the person who created the cuts to figure out a faster way to generate the cuts (perhaps running on other clusters) so that we don't have to wait for a month for everything.

**Comment by bmalumphy** [comment]
This makes sense. I'll get in contact with Ms. Laurin today when I get home around 7pm EST and see if we can figure something out before the weekend is done for me.

Also one reason that this probably won't work as is is that while season 2014 is 21000 TOD's long, season 205 is 60000 TOD's long. Just worth mentioning. I don't think four months for the data is viable.

I will also send her the code you and I have worked on. Hopefully there's some python shenanigans we can exploit that will help.

Thanks,
Bryan

On Jun 3, 2017, at 5:01 AM, Guan Yilun <notifications@github.com<mailto:notifications@github.com>> wrote:


Running cut generation of Feynman takes 3 hours / 100 TOD. In each season there is 20000 TODs, so it will take about 25 days to generate all cuts. This can be done but on the other hand, according to Fernando, the original author of the cuts generate the cuts in the timescale of days. Therefore, it would be good to correspond with Fernando and the person who created the cuts to figure out faster way to generate the cuts so that we don't have to wait for a month for every thing.

**Comment by guanyilun** [comment]
Running profiling for the find_cuts script 
```
python -m cProfile -s time find_cuts.py 1000 1010
```
gives results (top 4)
```
          8224558 function calls (8217714 primitive calls) in 67.464 seconds

   Ordered by: internal time 

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        8   40.404    5.051   40.404    5.051 {moby2.libactpol.get_glitch_cuts}
        8   11.121    1.390   11.121    1.390 {moby2.libactpol.dirfile_load_channels}
    61986    3.789    0.000    3.789    0.000 {method 'query' of '_mysql.connection' objects}
    34170    0.795    0.000    2.584    0.000 linalg.py:1733(lstsq)

```

**Comment by guanyilun** [comment]
Updated statistics from running 500 TODs is the following (showing the top 5)
```
         209285262 function calls (209210720 primitive calls) in 52985.763 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      494 44329.808   89.736 44329.808   89.736 {moby2.libactpol.get_glitch_cuts}
      494 7688.637   15.564 7688.637   15.564 {moby2.libactpol.dirfile_load_channels}
      988  308.454    0.312  308.485    0.312 fitpack2.py:441(__init__)
        1   96.247   96.247 52985.780 52985.780 find_cuts.py:1(<module>)
     2470   41.658    0.017   41.658    0.017 {moby2.libactpol.dirfile_load_channel}
  1163642   41.511    0.000  218.263    0.000 polynomial.py:396(polyfit)
```
It shows that 
```
get_glitch_cut -> 84%
moby2.libactpol.dirfile_load_channels -> 14.5%
rest -> 1.5%
```
so I think optimizing the double loop will only have an effect up to 1.5% increase.

**Comment by guanyilun** [comment]
Run parallel in Feynman is possible
